language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      xcode_sdk: macosx10.12
      sudo: required
    - os: osx
      osx_image: xcode8.2
      xcode_sdk: macosx10.12
      sudo: required
    - os: osx
      osx_image: xcode8.1
      xcode_sdk: macosx10.12
      sudo: required
    - os: osx
      osx_image: xcode8
      xcode_sdk: macosx10.11
      sudo: required
    - os: osx
      osx_image: xcode7.3
      xcode_sdk: macosx10.11
      sudo: required
branches:
  only:
    - master
install:
# Install Apple's NullAudio device. Travis' VMs don't have any audio devices installed.
  - sudo xcodebuild -project BGMApp/BGMAppTests/NullAudio/AudioDriverExamples.xcodeproj -target NullAudio DSTROOT="/" install
  - sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod || sudo killall coreaudiod
script:
# Build in a case-sensitive disk image to catch failures that only happen on case-sensitive filesystems.
  - hdiutil create -type SPARSEBUNDLE -fs 'Case-sensitive Journaled HFS+' -volname bgmbuild -nospotlight -verbose -attach -size 50m bgmbuild.dmg
  - sudo cp -r . /Volumes/bgmbuild
  - cd /Volumes/bgmbuild
# Install Background Music.
  - yes | ./build_and_install.sh
  - cat build_and_install.log
  - find */build/Release/*/ -type f -exec md5 {} \;
# Log the installed audio devices...
  - system_profiler SPAudioDataType
# ...and their IDs.
  - say -a '?'
# Check the BGM dirs and files were installed. (These fail if the dir/file isn't found.)
  - ls -la "/Applications/Background Music.app"
  - ls -la "/Library/Audio/Plug-Ins/HAL/Background Music Device.driver"
  - ls -la "/usr/local/libexec/BGMXPCHelper.xpc" || ls -la "/Library/Application Support/Background Music/BGMXPCHelper.xpc"
  - ls -la "/Library/LaunchDaemons/com.bearisdriving.BGM.XPCHelper.plist"
# Close BGMApp (which the install script opened).
  - osascript -e 'tell application "Background Music" to quit'
# Skip the UI tests until Travis has support for them.
  - BGMApp/BGMAppTests/UITests/travis-skip.py
# Run the tests.
  - xcodebuild -workspace BGM.xcworkspace -scheme 'Background Music Device' test
  - xcodebuild -workspace BGM.xcworkspace -scheme 'Background Music' test
  - xcodebuild -workspace BGM.xcworkspace -scheme 'BGMXPCHelper' test
# Uninstall Background Music.
  - yes | ./uninstall.sh
# Check the BGM dirs and files were removed.
  - if ls -la "/Applications/Background Music.app"; then false; fi
  - if ls -la "/Library/Audio/Plug-Ins/HAL/Background Music Device.driver"; then false; fi
  - if ls -la "/usr/local/libexec/BGMXPCHelper.xpc"; then false; fi
  - if ls -la "/Library/Application Support/Background Music/BGMXPCHelper.xpc"; then false; fi
  - if ls -la "/Library/LaunchDaemons/com.bearisdriving.BGM.XPCHelper.plist"; then false; fi
# Post on IRC when Travis builds finish.
notifications:
  irc: "irc.freenode.org#backgroundmusic"
